services:
  rocketchat:
    container_name: rocketchat
    image: registry.rocket.chat/rocketchat/rocket.chat:${RELEASE:-latest}
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.rocketchat.rule: Host(`${DOMAIN:-}`)
      traefik.http.routers.rocketchat.tls: "true"
      traefik.http.routers.rocketchat.entrypoints: https
      traefik.http.routers.rocketchat.tls.certresolver: le
    environment:
      MONGO_URL: "mongodb://mongodb7:27017/rocketchat?replicaSet=rs0"
      MONGO_OPLOG_URL: "mongodb://mongodb7:27017/local?replicaSet=rs0"
      ROOT_URL: http://localhost:9000
      PORT: 9000
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM:-}
      REG_TOKEN: ${REG_TOKEN:-}
    expose:
      - 9000
    ports:
      - "0.0.0.0:9000:9000"
    volumes:
      - uploads:/app/uploads

volumes:
  uploads: 

networks:
  default:
    external: true
    name: base